<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net10.0</TargetFramework><Nullable>enable</Nullable></PropertyGroup><ItemGroup><ProjectReference Include="..\Layers\Application\Lecture15.Application.csproj" /><ProjectReference Include="..\Layers\Infrastructure\Lecture15.Infrastructure.csproj" /><ProjectReference Include="..\Layers\Presentation\Lecture15.Presentation.csproj" /></ItemGroup></Project>
