<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net10.0</TargetFramework><Nullable>enable</Nullable></PropertyGroup><ItemGroup><ProjectReference Include="..\Layers\Application\Lecture13.Application.csproj" /><ProjectReference Include="..\Layers\Infrastructure\Lecture13.Infrastructure.csproj" /><ProjectReference Include="..\Layers\Presentation\Lecture13.Presentation.csproj" /></ItemGroup></Project>
