<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><ProjectReference Include="..\Layers\Application\Lecture10.Application.csproj" /><ProjectReference Include="..\Layers\Infrastructure\Lecture10.Infrastructure.csproj" /></ItemGroup></Project>
