<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\Lecture08.Application.csproj" />
    <ProjectReference Include="..\Domain\Lecture08.Domain.csproj" />
  </ItemGroup>
</Project>
