<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup><ProjectReference Include="..\Application\Lecture09.Application.csproj" /><ProjectReference Include="..\Domain\Lecture09.Domain.csproj" /></ItemGroup>
</Project>
